spring:
  profiles:
    active:
    - dev
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace

paginacao:
  qtd_por_pagina: 25
  
jwt:
  secret: _@HRL&L3tF?Z7ccj4z&L5!nU2B!Rjs3_
  expiration: 604800
---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ponto_inteligente?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    
---

spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: mem
    password: mem
    
  flyway:
    enabled: false
    
---
spring:
  profiles: prod

    
    