spring:
  profiles:
    active:
    - prod
  
---

spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ponto_inteligente?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    
---

spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: mem
    password: mem
    
  flyway:
    enabled: false
    
    